### ISSUE TITLE
Deprecation / consolidation with `next-sitemap`

### ISSUE THREAD

**Issue by leerob** [cansin/next-with-sitemap#16]
Hello!

I see you mentioned you're looking for maintainers since you no longer have time to work on this. I totally understand 😄 

Would you consider deprecating/archiving this package in favor of https://github.com/iamvishnusankar/next-sitemap? I believe this would help the community consolidate efforts on a single package for sitemaps 🙏 If you don't want to, totally understand.

Thank you so much!

**Comment by cansin** [comment]
@leerob I think you are right. Let me update the readme and archive the project 💯
